version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"            # Gateway for all AWS services
      - "4571:4571"
    environment:
      - SERVICES=ec2,s3,iam
      - DEBUG=1
    volumes:
      - ./volume:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
